### model
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.1
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: freeze
freeze_trainable_layers: 12
# freeze_trainable_modules: all
# freeze_trainable_modules: self_attn
# freeze_trainable_modules: mlp
freeze_trainable_modules: mlp, self_attn
# use_llama_pro: true
deepspeed: examples/deepspeed/ds_z0_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: beavertail_harmful
template: mistral
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/mistralv0.1-harmful/attn_ffn/sft_ntk_e4_layer12
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
